steps:
  - name: 'golang:1.11.1-stretch'
    entrypoint: 'go'
    args: ['build', '.']
    env: ['GO111MODULE=on']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/sinmetal/hellotime:v1.0.0', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/sinmetal/hellotime:v1.0.0"]
images: ['gcr.io/$PROJECT_ID/sinmetal/hellotime:v1.0.0']